New shell initialisation routines

diff --git a/share/bash_promt b/share/bash_promt
--- a/share/bash_promt
+++ b/share/bash_promt
@@ -1,20 +1,12 @@
 ## Try this: http://packages.debian.org/unstable/admin/molly-guard
 # This script creates a fancy promt for bash.
-# To try it out, use "source promt.sh"
 
-sh="$(ps -p $$ -o comm=)"
 
 function __git_ps1 {
 	# Do nothing, so no error will occur on systems without git
 	true
 }
 
-if [ -f "/usr/share/git/completion/git-completion.$sh" ]
-then
-	source "/usr/share/git/completion/git-completion.$sh"
-	GIT_PS1_SHOWDIRTYSTATE=yep
-	GIT_PS1_SHOWSTASHSTATE=yep
-fi
 
 function commpilePromt {
 	# Calculate the remaining space, considering the length of invisible color
@@ -37,13 +29,13 @@ ${pLineC}└─${pPromtC}>>${pNormalC} "
 }
 
 
-
 function precmd {
-	# == Create a notice if last command failed
+	## == Create a notice if last command failed
+	## This has to stay at the top, to get the right return value
 	local returncode=$?
 	
-	# Workaround: We need a character after the "\n" to be recognized by PS1,
-	# therefore we take the color code of the next line as our last bit.
+	## Workaround: We need a character after the "\n" to be recognized by PS1,
+	## therefore we take the color code of the next line as our last bit.
 	if [[ "${returncode}" == 0 ]]
 	then
 		pNotice="${pLineC}"
@@ -53,71 +45,49 @@ ${pLineC}"
 	fi
 	
 	
-	
-	# == Find out wether we are on a remote machine
-	if [ "$SSH_CONNECTION" ]
-	then
-		pHostC=${pHostRemoteC}
-	else
-		pHostC=${pHostLocalC}
-	fi
-	
-	
-	
-	# == Set title if terminal is xterm (from ubuntu .bashrc)
-	case "$TERM" in
-	xterm*|rxvt*)
-		echo -ne "\033]0;${fqdn} - ${USER}: ${pwd}\007"
-	;;
-	
-	*)
-	;;
-	esac
-	
-	
-	# == Try if the promt is long enough. otherwise short it
-	# ---- 1. try: full promt
-	# replaces $HOME dir with ~ ; dir level 3
+	## ==== Define Variables
+	## Creates in zsh a "%%" instead of "%", which messes with the line length
+	## calculation (until now ignored)
 	local git="$(__git_ps1 " (%s)")"
 	local pwd="$(echo "${PWD/#$HOME/~}" | sed  's/.*\/\(.*\/.*\/.*\)$/\1/')"
 	local time="$(date +%T)"
-	if [ -x /bin/hostname ]
-	then
-		pHost="$(hostname --long)"
-	else
-		pHost="$(cat /proc/sys/kernel/hostname)"
-	fi
-	local fqdn="$pHost"
 	
-	pLeftPart="${pLineC}┌───────┤${pHostC} ${pHost} ${pLineC}├───────┤${pPwdC} ${pwd}${git} ${pLineC}├"
+	
+	
+	
+	## ==== Set title if terminal is xterm
+	case "$TERM" in
+		xterm*|rxvt*)
+			echo -ne "\033]0;${S_HOST}: ${pwd} (${USER})\007"
+		;;
+	esac
+	
+	
+	## ==== Try if the promt is long enough. otherwise short it
+	## -- 1. try: full promt
+	## replaces $HOME dir with ~ ; dir level 3	
+	pLeftPart="${pLineC}┌───────┤${pHostC} ${S_HOST} ${pLineC}├───────┤${pPwdC} ${pwd}${git} ${pLineC}├"
 	pRightPart="───────┤${pTimeC} ${time} ${pLineC}├────"
+	commpilePromt 77 && return 0
 	
-	commpilePromt 49 && return 0
-	
-	# ---- 2. try: no clock
+	## -- 2. try: no clock
 	pRightPart=""
 	commpilePromt 27 && return 0
 	
-	# ---- 3. try: only hostname
-	if [ -x /bin/hostname ]
-	then
-		pHost="$(hostname --short)"
-	else
-		pHost="$(cut -d. -f1 /proc/sys/kernel/hostname)"
-	fi
-	pLeftPart="${pLineC}┌───────┤${pHostC} ${pHost} ${pLineC}├───────┤${pPwdC} ${pwd}${git} ${pLineC}├"
-	commpilePromt 27 && return 0
+	## -- 3. try: only hostname
+	pLeftPart="${pLineC}┌───────┤${pHostC} ${S_HOST} ${pLineC}├───────┤${pPwdC} ${pwd}${git} ${pLineC}├"
+	commpilePromt 55 && return 0
 	
-	# ---- 4. try: no git
+	## -- 4. try: no git
 	git=0
 	pLeftPart="${pLineC}┌───────┤${pPwdC} ${pwd} ${pLineC}├"
-	commpilePromt 5 && return 0
+	commpilePromt 33 && return 0
 	
-	# ---- 5. try: only pwd
+	## -- 5. try: only pwd
 	pLeftPart="${pLineC}┌───────┤${pPwdC} ${pwd} ${pLineC}├"
-	commpilePromt 5 && return 0
+	commpilePromt 33 && return 0
 	
-	# ---- 7. try: fall back, no graphical gimmicks
+	## -- 7. try: fall back, no graphical gimmicks
 	pLeftPart="${pPwdC}${pwd}"
 	pFill=""
 	commpilePromt 0
@@ -127,56 +97,83 @@ ${pLineC}"
 }
 
 
+prepareGit() {
+	if [ -f "/usr/share/git/completion/git-prompt.sh" ] ; then
+		source "/usr/share/git/completion/git-prompt.sh"
+		GIT_PS1_SHOWDIRTYSTATE=yep
+		GIT_PS1_SHOWSTASHSTATE=yep
+		GIT_PS1_SHOWUNTRACKEDFILES=yep
+	fi
+	
+	gitCompleteFile="/usr/share/git/completion/git-completion.$S_ACT_SHELL"
+	test -f "$gitCompleteFile"
+	return "$?"
+}
 
-# Define static things only once here at beginning, not at each promt creation!
 
-# == colors
-# ---- define
+case "$S_ACT_SHELL" in
+	"bash")
+		if prepareGit ; then
+			source "$gitCompleteFile"
+		fi
+		
+		npStart="\["
+		npEnd="\]"
+		;;
+	
+	"zsh")
+		if prepareGit ; then
+			fpath+="$gitCompleteFile"
+		fi
+		
+		npStart="%{"
+		npEnd="%}"
+		;;
+	
+	*)
+		## Harmless replacement for "non-printing" escape sequencees to maintain
+		## the correct length
+		npStart="\001\002"
+		npEnd="\001\002"
+		;;
+esac
 
-pNormalC=$(echo -e "\033[m")
-pLineC=$(echo -e "\033[0;36m")
-pRootC=$(echo -e "\033[1;31m")
-pRemoteC=$(echo -e "\033[1;35m")
-pUserC=$(echo -e "\033[1;32m")
-pTextC=$(echo -e "\033[1;33m")
+
+## ==== colors
+## -- define
+pNormalC=$(echo -e "$npStart\033[m$npEnd")
+pLineC=$(  echo -e "$npStart\033[0;36m$npEnd")
+pRootC=$(  echo -e "$npStart\033[1;31m$npEnd")
+pRemoteC=$(echo -e "$npStart\033[1;35m$npEnd")
+pUserC=$(  echo -e "$npStart\033[1;32m$npEnd")
+pTextC=$(  echo -e "$npStart\033[1;33m$npEnd")
 pHostLocalC=$pTextC
 pHostRemoteC=$pRemoteC
 pPwdC=$pTextC
 pTimeC=$pTextC
-pFailedNoticeC=$(echo -e "\033[1;31m")
+pFailedNoticeC=$(echo -e "$npStart\033[1;31m$npEnd")
 
-
-# ---- select depending on user
-
-if [[ "$UID" == 0 ]]
-then
+## -- select depending on user
+if [ "$UID" -eq 0 ] ; then
 	pPromtC="${pRootC}"
 else
 	pPromtC="${pUserC}"
 fi
 
-
-# == The rest of definitions
-
-case "$sh" in
-	"bash")
-		# check the window size after each command and, if necessary,
-		# update the values of LINES and COLUMNS.
-		shopt -s checkwinsize
-		
-		# Prevent that multiple bash instances overwrite the readline history of each
-		# other.
-		shopt -s histappend
-		;;
-esac
-
-export HISTCONTROL=ignoredups,erasedups
-export HISTSIZE=2000
-export HISTFILESIZE=2000
+## -- select depending on location
+if [ -n "$SSH_CONNECTION" ] ; then
+	pHostC=${pHostRemoteC}
+else
+	pHostC=${pHostLocalC}
+fi
 
 
-# This function will be called before PS1 is evaluated
+## ==== The rest of definitions
+## This function will be called before PS1 is evaluated
 PROMPT_COMMAND=precmd
 
-# Define the promt for multi line commands
+## Define the promt for multi line commands
 PS2="  ${pPromtC}>>${pNormalC} "
+
+## Clean up
+unset prepareGit
